app/blueprints/main.py
import base64
from logging import getLogger

from flask import Blueprint, redirect, render_template, request, url_for

from app.api_client import Client

main_bp = Blueprint("main", __name__)

client = Client(getLogger(__name__))


@main_bp.route("/")
def home():
    return render_template(
        "main/index.html",
        title="Page d'accueil",
        movies_now_playing=client.get_movies_now_playing(),
    )


@main_bp.route("/profile", methods=["GET", "POST"])
def profile():
    if request.method == "POST":
        profile_data = {}
        profile_data.update({"username": request.form.get("username")})
        profile_data.update({"mail": request.form.get("email")})
        profile_picture = request.files.get("file")
        if profile_picture and profile_picture != "":
            profile_data.update(
                {"profile_image": base64.b64encode(profile_picture.read()).decode()}
            )

        if profile_data:
            client.update_user(request.cookies["token"], profile_data)

        return redirect(url_for("main.profile"))

    return render_template(
        "main/profile.html",
        title="Profil",
        wishlist=client.get_wishlist(request.cookies["token"]),
    )


@main_bp.route("/about", methods=["GET"])
def about():
    return render_template("main/about.html", title="A propos")


@main_bp.route("/confidentiality", methods=["GET"])
def confidentiality():
    return render_template(
        "main/confidentiality.html", title="Politique de confidentialité"
    )


@main_bp.route("/licence", methods=["GET"])
def licence():
    return render_template("main/licence.html", title="Licence")

app/blueprints/movie.py
from logging import getLogger

from flask import Blueprint, flash, redirect, render_template, request, url_for

from app.api_client import Client

movie_bp = Blueprint("movie", __name__, url_prefix="/movies")

client = Client(getLogger(__name__))

movie_genres = client.get_movie_genres()


@movie_bp.route("/")
def home():
    params = {
        "sort_by": request.args.get("sort_by"),
        "with_genres": request.args.getlist("with_genres"),
        "release_date.gte": request.args.get("release_date.gte"),
        "release_date.lte": request.args.get("release_date.lte"),
        "with_runtime.gte": request.args.get("with_runtime.gte"),
        "with_runtime.lte": request.args.get("with_runtime.lte"),
    }
    movies = client.discover_movies(params)
    return render_template(
        "movie/index.html",
        title="Films",
        movies=movies,
        movie_genres=movie_genres,
    )


@movie_bp.route("/search")
def search():
    results = client.get_movie_by_title(request.args.get("title") or "")
    return render_template(
        "movie/search.html",
        title="Recherche",
        movies=results["movies"],
        total_results=results["total_results"],
    )


@movie_bp.route("/popular")
def popular():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films populaires",
        movies=client.get_popular_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/trending")
def trending():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films tendances",
        movies=client.get_trending_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/upcoming")
def upcoming():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films à venir",
        movies=client.get_upcoming_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/top_rated")
def top_rated():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films les mieux notés",
        movies=client.get_top_rating_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/<int:movie_id>")
def details(movie_id: int):
    token = request.cookies.get("token")
    collections = client.get_all_collections(token) if token else None
    return render_template(
        "movie/details.html",
        title="Détails du film",
        movie=client.get_movie_by_id(movie_id, token),
        credits=client.get_movie_credits(movie_id),
        collections=collections,
    )


@movie_bp.route("/<int:movie_id>/wishlist", methods=["POST"])
def wishlist(movie_id: int):
    token = request.cookies.get("token")

    res = client.add_to_wishlist(token, movie_id)
    if res.get("error"):
        flash(res["error"], "error")

    return redirect(url_for("movie.details", movie_id=movie_id))

app/blueprints/person.py
from logging import getLogger

from flask import Blueprint, render_template, request

from app.api_client import Client

person_bp = Blueprint("person", __name__, url_prefix="/person")

client = Client(getLogger(__name__))


@person_bp.route("/")
def popular():
    persons = client.get_popular_persons()
    return render_template(
        "person/popular.html", title="Liste d'artistes", persons=persons
    )


@person_bp.route("/search")
def search():
    name = request.args.get("name")
    results = client.get_artist_by_name(name)
    return render_template(
        "person/search.html",
        title="Recherche d'artistes",
        persons=results["persons"],
        total_results=results["total_results"],
    )


@person_bp.route("/<int:person_id>")
def details(person_id: int):
    person = client.get_person(person_id)

    def get_sort_date(credit):
        if credit["media_type"] == "tv" and credit.get("first_air_date"):
            return credit["first_air_date"]
        elif credit.get("release_date"):
            return credit["release_date"]
        else:
            return "1900-01-01"

    person["combined_credits"]["cast"] = sorted(
        person["combined_credits"]["cast"], key=get_sort_date, reverse=True
    )

    person["combined_credits"]["crew"] = sorted(
        person["combined_credits"]["crew"], key=get_sort_date, reverse=True
    )
    return render_template(
        "person/details.html", title="Détails d'un acteur", person=person
    )

app/templates/main/about.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <header class="py-6 mt-20">
        <div class="container mx-auto px-4">
            <h1 class="text-3xl font-bold">À propos de Filmy</h1>
        </div>
    </header>

    <main class="container mx-auto px-4 py-8">
        <section class="bg-white shadow-md rounded-lg p-6">
            <h2 class="text-2xl font-semibold mb-4">Notre projet</h2>
            <p class="mb-4">Cette application de vidéothèque a été développée dans le cadre de la formation en Master Réseaux et Télécom à l'Université de Reims pour la période 2024-2025.</p>
            <p class="mb-4">L'objectif principal de cette application est de permettre aux utilisateurs de gérer et explorer leur collection de films et séries de manière intuitive et efficace.</p>
        </section>

        <section class="bg-white shadow-md rounded-lg p-6 mt-8">
            <h2 class="text-2xl font-semibold mb-4">Les auteurs</h2>
            <ul class="list-disc list-inside">
                <li>Gaétan Lemont</li>
                <li>Antoine Maréchal</li>
            </ul>
        </section>

        <section class="bg-white shadow-md rounded-lg p-6 mt-8">
            <h2 class="text-2xl font-semibold mb-4">Notre mission</h2>
            <p>Nous visons à offrir une solution simple, moderne et performante pour gérer les vidéothèques personnelles tout en améliorant nos compétences en développement web et en gestion de projet.</p>
        </section>
    </main>
{% endblock %}

app/templates/main/confidentiality.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <header class="py-6 mt-20">
        <div class="container mx-auto px-4">
            <h1 class="text-3xl font-bold">Politique de Confidentialité</h1>
        </div>
    </header>

    <main class="container mx-auto px-4 py-8">
        <section class="bg-white shadow-md rounded-lg p-6">
            <h2 class="text-2xl font-semibold mb-4">Introduction</h2>
            <p class="mb-4">Nous accordons une grande importance à la confidentialité de vos données. Cette politique explique comment nous collectons, utilisons et protégeons vos informations personnelles.</p>
        </section>

        <section class="bg-white shadow-md rounded-lg p-6 mt-8">
            <h2 class="text-2xl font-semibold mb-4">Données collectées</h2>
            <p class="mb-4">Nous collectons uniquement les données nécessaires au fonctionnement de l'application, telles que :
                <ul class="list-disc list-inside">
                    <li>Votre adresse e-mail</li>
                    <li>Votre nom d'utilisateur</li>
                </ul>
            </p>
        </section>

        <section class="bg-white shadow-md rounded-lg p-6 mt-8">
            <h2 class="text-2xl font-semibold mb-4">Utilisation des données</h2>
            <p class="mb-4">Vos données sont utilisées uniquement pour :
                <ul class="list-disc list-inside">
                    <li>Fournir des fonctionnalités personnalisées</li>
                    <li>Créer le système de collection</li>
                </ul>
            </p>
        </section>

        <section class="bg-white shadow-md rounded-lg p-6 mt-8">
            <h2 class="text-2xl font-semibold mb-4">Protection des données</h2>
            <p class="mb-4">Nous mettons en œuvre des mesures de sécurité appropriées pour protéger vos données contre tout accès non autorisé, modification, divulgation ou destruction.</p>
        </section>
    </main>
{% endblock %}

app/templates/main/index.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<section class="bg-center bg-no-repeat bg-cover bg-[url('https://img.freepik.com/vecteurs-libre/banniere-cinema-ligne-clapet-ouvert-bande-film_1419-2242.jpg')] bg-gray-700 bg-blend-multiply p-5">
    <div class="px-4 mx-auto max-w-screen-xl text-center lg:py-20">
        <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl">Bienvenue sur Filmy</h1>
        <p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48">LA vidéothèque qui va changer votre vie !</p>
        <form id="searchForm" class="mx-auto relative w-full" action="{{ url_for('movie.search') }}" method="get">
            <div class="flex">
                <button id="dropdown-button" data-dropdown-toggle="dropdown" class="flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-s-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700 dark:text-white dark:border-gray-600" type="button">
                    Films <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"></path>
                </svg></button>
                <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-button">
                        <li>
                            <button type="button" class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-search-type="person">Artistes</button>
                        </li>
                        <li>
                            <button type="button" class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-search-type="movie">Films</button>
                        </li>
                        {% if is_connected %}
                            <li>
                                <button type="button" class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-search-type="collection">Mes collections</button>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <input type="search" id="search-dropdown" name="title" class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 border-s-gray-50 border-s-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500" placeholder="Chercher un film, un artiste..." required />
                <button type="submit" class="flex-shrink-0 px-4 text-sm font-medium text-white bg-blue-700 border border-blue-700 rounded-e-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
                    <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"></path>
                    </svg>
                    <span class="sr-only">Chercher</span>
                </button>
            </div>
        </form>
    </div>
</section>

<div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-button">
        <li>
            <button type="button" class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-search-type="person">Artistes</button>
        </li>
        <li>
            <button type="button" class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" data-search-type="movie">Films</button>
        </li>
    </ul>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('searchForm');
    const searchInput = document.getElementById('search-dropdown');
    const dropdownButtons = document.querySelectorAll('[data-search-type]');
    const dropdownButtonText = document.getElementById('dropdown-button');

    dropdownButtons.forEach(button => {
        button.addEventListener('click', function() {
            const searchType = this.getAttribute('data-search-type');
            if (searchType === 'movie') {
                form.action = "{{ url_for('movie.search') }}";
                searchInput.name = 'title';
                dropdownButtonText.textContent = 'Films';
            } else {
                form.action = "{{ url_for('person.search') }}";
                searchInput.name = 'name';
                dropdownButtonText.textContent = 'Artistes';
            }
        });
    });
});
</script>

<div class="p-5 w-2/3 mx-auto flex flex-1 flex-col">
    <p class="text-2xl font-bold">Actuellement au cinéma</p>
    <div id="carousel" class="flex space-x-4 overflow-x-auto scroll-smooth">
        {% for movie in movies_now_playing %}
        <div class="w-48 flex-shrink-0 bg-white rounded-lg shadow p-4">
            <a href="{{ url_for('movie.details', movie_id=movie.id_tmdb) }}">
                <img class="rounded-t-lg" src="https://image.tmdb.org/t/p/w200/{{ movie.poster_path }}" alt="{{ movie.original_title }}" loading="lazy" />
            </a>
            <h3 class="text-sm font-bold">{{ movie.title }}</h3>
            <p class="text-gray-500 text-sm">{{ movie.release_date|strftime }}</p>
        </div>
        {% endfor %}
    </div>
</div>

<footer class="bg-yellow-400 rounded-lg m-4 text-white font-bold">
    <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
      <span class="text-sm sm:text-center">© 2024 <a href="/" class="hover:underline">Filmy™</a>. Tous droits réservés.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm sm:mt-0">
        <li>
            <a href="{{ url_for('main.about') }}" class="hover:underline me-4 md:me-6">A propos</a>
        </li>
        <li>
            <a href="{{ url_for('main.confidentiality') }}" class="hover:underline me-4 md:me-6">Politique de confidentialité</a>
        </li>
        <li>
            <a href="{{ url_for('main.licence') }}" class="hover:underline me-4 md:me-6">Licence</a>
        </li>
    </ul>
    </div>
</footer>

{% endblock %}

app/templates/main/licence.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<header class="py-6 mt-20">
        <div class="container mx-auto px-4">
            <h1 class="text-3xl font-bold">Licence</h1>
        </div>
    </header>

    <main class="container mx-auto px-4 py-8">
        <section class="bg-white shadow-md rounded-lg p-6">
            <h2 class="text-2xl font-semibold mb-4">Introduction</h2>
            <p class="mb-4">Cette application est distribuée sous la licence MIT. Cela vous permet d'utiliser, copier, modifier et distribuer librement le logiciel, tant que vous incluez une copie de la licence originale dans vos distributions.</p>
        </section>

        <section class="bg-white shadow-md rounded-lg p-6 mt-8">
            <h2 class="text-2xl font-semibold mb-4">Conditions principales</h2>
            <p class="mb-4">La licence MIT impose les conditions suivantes :
                <ul class="list-disc list-inside">
                    <li>Le logiciel est fourni "tel quel", sans aucune garantie.</li>
                    <li>Le détenteur des droits d'auteur ne peut être tenu responsable de tout dommage résultant de l'utilisation du logiciel.</li>
                    <li>Une copie de la licence doit être incluse avec toute distribution du logiciel.</li>
                </ul>
            </p>
        </section>

        <section class="bg-white shadow-md rounded-lg p-6 mt-8">
            <h2 class="text-2xl font-semibold mb-4">Texte complet de la licence</h2>
            <pre class="bg-gray-100 p-4 rounded overflow-x-auto">
The MIT License (MIT)

Copyright (c) 2024-2025 Université de Reims

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
            </pre>
        </section>
    </main>
{% endblock %}

app/templates/main/profile.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="bg-gray-100 flex flex-col items-center py-16 mt-10 h-full">
    <section id="profile-section" class="bg-white shadow-lg rounded-lg p-6 w-full max-w-sm mb-8">
        <div class="flex flex-col items-center">
            <img
                src="{{ 'data:image/png;base64,' + user_data['profile_image']  if user_data['profile_image'] else url_for('static', filename='images/Default_pfp.jpg') }}"
                alt="Photo de profil actuelle"
                class="w-[165px] h-[165px] rounded-full border-2 border-blue-500 mb-4">
            <h1 class="text-xl font-semibold text-gray-800">{{ user_data["username"] }}</h1>
            <p class="text-gray-600">{{ user_data["mail"] }}</p>
            <div class="mt-6 flex space-x-4">
                <button
                    id="edit-profile-button"
                    class="px-4 py-2 text-sm font-medium text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:ring-2 focus:ring-blue-300">
                    Modifier le profil
                </button>
            </div>
        </div>
    </section>

    <section id="profile-section-edit" class="hidden bg-white shadow-lg rounded-lg p-6 w-full max-w-sm mb-8">
        <form class="mt-4 space-y-4" action="{{ url_for('main.profile') }}" method="post" enctype="multipart/form-data">
            <div class="flex items-center justify-center">
                <div class="relative flex items-center justify-center w-[165px] h-[165px] transition-all duration-300">
                    <input id="file" name="file" type="file" class="hidden" onchange="loadFile(event)" />
                    <img
                        src="{{ 'data:image/png;base64,' + user_data['profile_image']  if user_data['profile_image'] else url_for('static', filename='images/Default_pfp.jpg') }}"
                        id="output"
                        alt="Nouvelle photo de profil"
                        class="absolute w-[165px] h-[165px] object-cover border-2 border-blue-500 rounded-full shadow-[0_0_10px_0_rgba(255,255,255,0.35)]">
                    <label
                        for="file"
                        class="absolute flex items-center justify-center w-[165px] h-[165px] cursor-pointer transition-all duration-200 bg-transparent text-transparent rounded-full hover:bg-black hover:bg-opacity-80 hover:text-white z-10">
                        <span class="inline-flex items-center justify-center h-8 px-2">Changer l'image</span>
                    </label>
                </div>
            </div>
            <label for="username-input" class="block text-sm font-medium text-gray-700">Nom d'utilisateur</label>
            <input
                id="username-input"
                name="username"
                type="text"
                value="{{ user_data["username"] }}"
                class="text-gray-800 border border-gray-300 rounded-lg p-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-300"
                required>

            <label for="email-input" class="block text-sm font-medium text-gray-700">Adresse e-mail</label>
            <input
                id="email-input"
                name="email"
                type="email"
                value="{{ user_data["mail"] }}"
                class="text-gray-800 border border-gray-300 rounded-lg p-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-300"
                required>

            <div class="mt-6 flex space-x-4 justify-center">
                <button
                    id="save-profile-button"
                    type="submit"
                    class="px-4 py-2 text-sm font-medium text-white bg-green-500 rounded-lg hover:bg-green-600 focus:ring-2 focus:ring-green-300">
                    Enregistrer
                </button>
                <button
                    id="cancel-edit-button"
                    type="button"
                    class="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-lg hover:bg-gray-300 focus:ring-2 focus:ring-gray-400">
                    Annuler
                </button>
            </div>
        </form>
    </section>

    {% if wishlist %}
    <section class="w-full max-w-4xl bg-white shadow-lg rounded-lg p-6">
        <h3 class="text-lg font-medium text-gray-700 mb-2">Liste de souhaits</h3>
        <ul class="space-y-2">
            {% for wish in wishlist %}
                <li class="bg-gray-100 p-3 rounded-lg flex justify-between items-center">
                    <a href="{{ url_for('movie.details', movie_id=wish.id) }}" class="text-gray-800">{{ wish.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}
</div>

<script>
const loadFile = function (event) {
    const image = document.getElementById("output");
    image.src = URL.createObjectURL(event.target.files[0]);
    event.preventDefault();
};

const profileSection = document.getElementById("profile-section");
const profileSectionEdit = document.getElementById("profile-section-edit");

document.getElementById("edit-profile-button").addEventListener("click", () => {
    profileSection.classList.add("hidden");
    profileSectionEdit.classList.replace("hidden", "block");
});

document.getElementById("cancel-edit-button").addEventListener("click", () => {
    profileSectionEdit.classList.replace("block", "hidden");
    profileSection.classList.replace("hidden", "block");
});
</script>
{% endblock %}