app/blueprints/collection.py
import base64
from logging import getLogger

import flask
from flask import Blueprint, redirect, render_template, request, url_for

from app.api_client import Client

collection_bp = Blueprint("collection", __name__, url_prefix="/collection")

client = Client(getLogger(__name__))


@collection_bp.route("/")
def hub():
    return render_template(
        "collection/index.html",
        title="Liste de vos collections",
        collections=client.get_all_collections(request.cookies["token"]),
    )


@collection_bp.route("/<int:collection_id>")
def view(collection_id):
    collection = client.get_collection(request.cookies["token"], collection_id)
    return render_template(
        "collection/view.html", title="Vue d'une collection", collection=collection
    )


@collection_bp.route("/add_collection_item", methods=["POST"])
def add_collection_item():
    collection = request.form.get("collection")
    state = request.form.get("state")
    film_id = request.form.get("film-id")

    is_wishlist = request.args.get("wishlist")

    if request.cookies["token"]:
        if is_wishlist:
            res = client.transfer_wishlist_to_collection(
                request.cookies["token"], collection, film_id, state
            )
        else:
            res = client.add_item_into_collection(
                request.cookies["token"], collection, film_id, state
            )
        if res.get("error"):
            flask.flash(res["error"], "error")
        return redirect(url_for("movie.details", movie_id=film_id))

    return render_template(
        "main/index.html",
        title="Page d'accueil",
        movies_now_playing=client.get_movies_now_playing(),
    )


@collection_bp.route("/add", methods=["POST"])
def add_collection():
    name = request.form.get("name")
    token = request.cookies["token"]
    if token:
        res = client.create_collection(token, name)
        if res.get("error"):
            flask.flash(res["error"], "error")

        flask.flash("Film bien ajouté à votre collection !", "success")
        return redirect(url_for("collection.hub"))

    return render_template(
        "main/index.html",
        title="Page d'accueil",
        movies_now_playing=client.get_movies_now_playing(),
    )


@collection_bp.route("/<int:collection_id>/delete", methods=["POST"])
def delete_collection(collection_id):
    collection = client.delete_collection(request.cookies["token"], collection_id)
    if collection.get("error"):
        flask.flash(collection["error"], "error")
        return redirect(url_for("collection.hub"))

    flask.flash("Collection bien supprimée !", "success")
    return redirect(url_for("collection.hub"))


@collection_bp.route("/<int:collection_id>/edit", methods=["GET", "POST"])
def edit(collection_id):
    if request.method == "POST":
        collection_data = {}
        collection_data.update({"name": request.form.get("name")})
        picture = request.files.get("file")
        if picture and picture != "":
            collection_data.update(
                {"picture": base64.b64encode(picture.read()).decode()}
            )

        if collection_data:
            res = client.update_collection(
                request.cookies["token"], collection_id, collection_data
            )
            if res.get("error"):
                flask.flash(res["error"], "error")
                return redirect(url_for("collection.edit", collection_id=collection_id))

        flask.flash("Collection bien mise à jour !", "success")
        return redirect(url_for("collection.view", collection_id=collection_id))

    collection = client.get_collection(request.cookies["token"], collection_id)
    return render_template(
        "collection/edit.html", title="Edition d'une collection", collection=collection
    )


@collection_bp.route("/<int:collection_id>/<int:movie_id>/update", methods=["POST"])
def update_item(collection_id: int, movie_id: int):
    token = request.cookies.get("token")
    if token:
        item_data = {}
        borrowed = request.form.get("borrowed")
        if borrowed:
            item_data.update({"borrowed": borrowed == "true"})
        favorite = request.form.get("favorite")
        if favorite:
            item_data.update({"favorite": favorite == "true"})

        res = client.update_collection_item(token, collection_id, movie_id, item_data)
        if res.get("error"):
            flask.flash(res["error"], "error")
            return redirect(
                url_for("movie.details", collection_id=collection_id, movie_id=movie_id)
            )

        flask.flash("Opération menée avec succès !", "success")
        return redirect(
            url_for("movie.details", collection_id=collection_id, movie_id=movie_id)
        )

    return redirect(url_for("main.home"))


@collection_bp.route("/<int:collection_id>/<int:movie_id>/delete", methods=["POST"])
def delete_collection_item(collection_id, movie_id):
    collection = client.delete_collection_item(
        request.cookies["token"], collection_id, movie_id
    )
    if collection.get("error"):
        flask.flash(collection["error"], "error")
        return redirect(url_for("collection.hub"))

    flask.flash("Film bien supprimé de votre collection !", "success")
    return redirect(url_for("collection.view", collection_id=collection_id))

app/templates/collection/edit.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<form class="mt-4 space-y-4 h-full flex flex-col justify-center items-center mx-40" action="{{ url_for('collection.edit', collection_id=collection.id) }}" method="post" enctype="multipart/form-data">
    <div class="flex items-center justify-center">
        <div class="relative flex items-center justify-center w-[165px] h-[165px] transition-all duration-300">
            <input id="file" name="file" type="file" class="hidden" onchange="loadFile(event)" />
            <img
                src="{{ 'data:image/png;base64,' + collection['picture'] if collection['picture'] else url_for('static', filename='images/default-movie.png.jpg') }}"
                id="output"
                alt="Nouvelle photo de profil"
                class="absolute w-[165px] h-[165px] object-cover border-2 border-blue-500 shadow-[0_0_10px_0_rgba(255,255,255,0.35)]">
            <label
                for="file"
                class="absolute flex items-center justify-center w-[165px] h-[165px] cursor-pointer transition-all duration-200 bg-transparent text-transparent hover:bg-black hover:bg-opacity-80 hover:text-white z-10">
                <span class="inline-flex items-center justify-center h-8 px-2">Changer l'image</span>
            </label>
        </div>
    </div>
    <label for="name-input" class="block text-sm font-medium text-gray-700">Nom de la collection</label>
    <input
        id="name-input"
        name="name"
        type="text"
        value="{{ collection["name"] }}"
        class="text-gray-800 border border-gray-300 rounded-lg p-2 w-full focus:outline-none focus:ring-2 focus:ring-blue-300"
        required>

    <div class="mt-6 flex space-x-4 justify-center">
        <button
            id="save-profile-button"
            type="submit"
            class="px-4 py-2 text-sm font-medium text-white bg-green-500 rounded-lg hover:bg-green-600 focus:ring-2 focus:ring-green-300">
            Enregistrer
        </button>
    </div>
</form>

<script>
const loadFile = function (event) {
    const image = document.getElementById("output");
    image.src = URL.createObjectURL(event.target.files[0]);
    event.preventDefault();
};

const profileSection = document.getElementById("profile-section");
const profileSectionEdit = document.getElementById("profile-section-edit");

document.getElementById("edit-profile-button").addEventListener("click", () => {
    profileSection.classList.add("hidden");
    profileSectionEdit.classList.replace("hidden", "block");
});
</script>
{% endblock %}

app/templates/collection/index.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="flex mt-20 p-4 justify-center items-center gap-5">
        <h1 class="text-4xl font-bold text-center">{{ title }}</h1>
        <button data-modal-target="crud-modal" data-modal-toggle="crud-modal" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
          Ajouter une collection
        </button>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 lg:mx-40">
    {% for collection in collections %}
    <div class="relative max-w-xs p-4 hover:cursor-pointer hover:animate-pulse duration-300 group">
        <a href="{{ url_for('collection.view', collection_id=collection.id) }}">
            {% set url = 'data:image/png;base64,' + collection['picture']  if collection['picture'] else 'none' %}
            <div class="bg-blue-500 text-white p-12 rounded-lg shadow-lg flex flex-col items-center bg-center bg-no-repeat bg-cover bg-blend-multiply" style="background-image: url({{ url }});">
                <div class="flex items-center justify-center w-24 h-24 bg-black bg-opacity-25 rounded-full">
                    <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.752 11.168l-6.4-3.2A1 1 0 007 8v8a1 1 0 001.352.936l6.4-3.2a1 1 0 000-1.768z"></path>
                    </svg>
                </div>
                <p class="mt-4 text-center text-lg font-semibold">{{ collection.name }}</p>
            </div>
        </a>
        {% if collection.name != 'Defaut' %}
        <div class="absolute top-0 right-0 p-4 gap-3 flex bg-gray-200 rounded-lg shadow-lg">
            <a href="{{ url_for('collection.edit', collection_id=collection.id) }}">
                <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M3 21v-3l12-12 3 3-12 12H3z" fill="#FFD700"></path>
                    <path d="M15 6l3 3 2-2-3-3-2 2z" fill="#808080"></path>
                    <path d="M3 21h3l12-12-3-3L3 18v3z" fill="#FFA500"></path>
                </svg>
            </a>
            <form action="{{ url_for('collection.delete_collection', collection_id=collection.id) }}" method="POST">
                <button type="submit">
                    <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect x="5" y="7" width="14" height="14" fill="red"></rect>
                        <rect x="3" y="4" width="18" height="3" fill="darkred"></rect>
                        <line x1="8" y1="10" x2="8" y2="18" stroke="black" stroke-width="2"></line>
                        <line x1="12" y1="10" x2="12" y2="18" stroke="black" stroke-width="2"></line>
                        <line x1="16" y1="10" x2="16" y2="18" stroke="black" stroke-width="2"></line>
                    </svg>
                </button>
            </form>
        </div>
        {% endif %}
    </div>
    {% endfor %}
</div>

<div id="crud-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                    Ajouter une collection
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="crud-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>

            <form class="p-4 md:p-5" action="{{ url_for('collection.add_collection') }}" method="post">
                <div class="col-span-2 mb-2">
                    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nom</label>
                    <input type="text" name="name" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Nom de la collection" required="">
                </div>
                <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    <svg class="me-1 -ms-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path></svg>
                    Ajouter une collection
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/collection/view.html
{% extends "layout.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
{% set url = 'data:image/png;base64,' + collection['picture']  if collection['picture'] else 'none' %}

<div class="min-h-screen text-white pt-32 bg-gray-500 bg-center bg-no-repeat bg-cover bg-blend-multiply" style="background-image: url({{ url }});">
    <div class="container mx-auto p-6">
        <div class="flex justify-between items-center mb-8">
            <div class="flex items-center gap-4">
                <h1 class="text-2xl font-bold">{{ collection.name }}</h1>
                <span class="text-sm bg-gray-700 px-2 py-1 rounded">{{ collection["items"]|length }} items</span>
                <span class="text-sm bg-gray-700 px-2 py-1 rounded">FR</span>
                {% if collection.name != 'Defaut' %}
                <a href="{{ url_for('collection.edit', collection_id=collection.id) }}" class="hover:text-gray-300 bg-gray-700 p-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"></path>
                    </svg>
                </a>
                {% endif %}
            </div>
        </div>

        <section>
            <h2 class="text-xl font-semibold mb-6">Films</h2>
            <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-4">
                {% for collection_item in collection["items"] %}
                <div class="relative group">
                    <a href="{{ url_for("movie.details", movie_id=collection_item.film.id, collection_id=collection.id) }}">
                        <img src="{{ "https://image.tmdb.org/t/p/w500" + collection_item.film.poster_path if collection_item.film.poster_path else url_for('static', filename='images/default-movie.png') }}" alt="{{ collection_item.film.title }}" class="w-full rounded-lg shadow-lg transition-transform duration-300 group-hover:scale-105">
                    </a>
                        <div class="absolute top-0 right-0 p-2 bg-gray-200 rounded-lg shadow-lg">
                            <form action="{{ url_for('collection.delete_collection_item', collection_id=collection.id, movie_id=collection_item.film.id) }}" method="POST">
                                <button type="submit">
                                    <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <rect x="5" y="7" width="14" height="14" fill="red"></rect>
                                        <rect x="3" y="4" width="18" height="3" fill="darkred"></rect>
                                        <line x1="8" y1="10" x2="8" y2="18" stroke="black" stroke-width="2"></line>
                                        <line x1="12" y1="10" x2="12" y2="18" stroke="black" stroke-width="2"></line>
                                        <line x1="16" y1="10" x2="16" y2="18" stroke="black" stroke-width="2"></line>
                                    </svg>
                                </button>
                            </form>
                        </div>
                    <div class="absolute bottom-0 left-0 right-0 p-2 bg-gradient-to-t from-black to-transparent">
                        <h3 class="text-sm font-medium flex justify-between items-center">
                            <div class="flex items-center">
                                {% if collection_item.favorite %}
                                    <svg data-tooltip-target="tooltip-bottom" data-tooltip-placement="bottom" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" class="h-6 w-6">
                                        <polygon points="50,5 61,38 95,38 66,57 76,90 50,70 24,90 34,57 5,38 39,38" fill="yellow" stroke="black" stroke-width="2"></polygon>
                                    </svg>
                                    <div id="tooltip-bottom" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
                                        Favori
                                        <div class="tooltip-arrow" data-popper-arrow></div>
                                    </div>
                                {% endif %}
                                {% if collection_item.borrowed %}
                                    <svg data-tooltip-target="tooltip-bottom-borrowed" data-tooltip-placement="bottom" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" class="h-10 w-10">
                                        <rect x="15" y="30" width="70" height="40" fill="black" stroke="white" stroke-width="2"></rect>
                                        <circle cx="30" cy="50" r="8" fill="white"></circle>
                                        <circle cx="70" cy="50" r="8" fill="white"></circle>
                                    </svg>
                                    <div id="tooltip-bottom-borrowed" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
                                        Prêté
                                        <div class="tooltip-arrow" data-popper-arrow></div>
                                    </div>
                                {% endif %}
                            </div>
                            {{ collection_item.film.title }}
                        </h3>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
    </div>
</div>
{% endblock %}