app/blueprints/movie.py
from logging import getLogger

from flask import Blueprint, flash, redirect, render_template, request, url_for

from app.api_client import Client

movie_bp = Blueprint("movie", __name__, url_prefix="/movies")

client = Client(getLogger(__name__))

movie_genres = client.get_movie_genres()


@movie_bp.route("/")
def home():
    params = {
        "sort_by": request.args.get("sort_by"),
        "with_genres": request.args.getlist("with_genres"),
        "release_date.gte": request.args.get("release_date.gte"),
        "release_date.lte": request.args.get("release_date.lte"),
        "with_runtime.gte": request.args.get("with_runtime.gte"),
        "with_runtime.lte": request.args.get("with_runtime.lte"),
    }
    movies = client.discover_movies(params)
    return render_template(
        "movie/index.html",
        title="Films",
        movies=movies,
        movie_genres=movie_genres,
    )


@movie_bp.route("/search")
def search():
    results = client.get_movie_by_title(request.args.get("title") or "")
    return render_template(
        "movie/search.html",
        title="Recherche",
        movies=results["movies"],
        total_results=results["total_results"],
    )


@movie_bp.route("/popular")
def popular():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films populaires",
        movies=client.get_popular_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/trending")
def trending():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films tendances",
        movies=client.get_trending_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/upcoming")
def upcoming():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films à venir",
        movies=client.get_upcoming_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/top_rated")
def top_rated():
    page = request.args.get("page", 1, type=int)

    return render_template(
        "movie/index.html",
        title="Films les mieux notés",
        movies=client.get_top_rating_movies(page=page),
        movie_genres=movie_genres,
    )


@movie_bp.route("/<int:movie_id>")
def details(movie_id: int):
    token = request.cookies.get("token")
    collections = client.get_all_collections(token) if token else None
    return render_template(
        "movie/details.html",
        title="Détails du film",
        movie=client.get_movie_by_id(movie_id, token),
        credits=client.get_movie_credits(movie_id),
        collections=collections,
    )


@movie_bp.route("/<int:movie_id>/wishlist", methods=["POST"])
def wishlist(movie_id: int):
    token = request.cookies.get("token")

    res = client.add_to_wishlist(token, movie_id)
    if res.get("error"):
        flash(res["error"], "error")

    return redirect(url_for("movie.details", movie_id=movie_id))

app/blueprints/person.py
from logging import getLogger

from flask import Blueprint, render_template, request

from app.api_client import Client

person_bp = Blueprint("person", __name__, url_prefix="/person")

client = Client(getLogger(__name__))


@person_bp.route("/")
def popular():
    persons = client.get_popular_persons()
    return render_template(
        "person/popular.html", title="Liste d'artistes", persons=persons
    )


@person_bp.route("/search")
def search():
    name = request.args.get("name")
    results = client.get_artist_by_name(name)
    return render_template(
        "person/search.html",
        title="Recherche d'artistes",
        persons=results["persons"],
        total_results=results["total_results"],
    )


@person_bp.route("/<int:person_id>")
def details(person_id: int):
    person = client.get_person(person_id)

    def get_sort_date(credit):
        if credit["media_type"] == "tv" and credit.get("first_air_date"):
            return credit["first_air_date"]
        elif credit.get("release_date"):
            return credit["release_date"]
        else:
            return "1900-01-01"

    person["combined_credits"]["cast"] = sorted(
        person["combined_credits"]["cast"], key=get_sort_date, reverse=True
    )

    person["combined_credits"]["crew"] = sorted(
        person["combined_credits"]["crew"], key=get_sort_date, reverse=True
    )
    return render_template(
        "person/details.html", title="Détails d'un acteur", person=person
    )

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='dist/css/output.css')}}">
    <link rel="icon" type="image/png" href="{{url_for('static', filename='filmy-logo.png')}}">
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>

<body class="flex flex-col h-screen">
    <nav id="navbar" class="fixed top-0 left-0 right-0 px-2 sm:px-4 py-2.5 bg-yellow-400 transition-transform duration-300 z-50">
    <div class="container flex flex-wrap items-center justify-between mx-auto">
        <a href="/" class="flex items-center">
            <img src="{{url_for('static', filename='images/filmy-logo.png')}}" class="h-9 mr-3 sm:h-12" alt="Filmy Logo">
            <span class="self-center text-2xl font-semibold whitespace-nowrap">Filmy</span>
        </a>
        <div class="flex md:order-2 gap-5 items-center">
            {% if is_connected %}
            <a href="{{ url_for('main.profile') }}" class="flex bg-white rounded-full focus:ring-2 focus:ring-gray-300" id="user-menu-button" aria-expanded="false" data-dropdown-placement="bottom">
                <img class="w-12 h-12 rounded-full" src="{{ 'data:image/png;base64,' + user_data['profile_image'] if user_data['profile_image'] else url_for('static', filename='images/Default_pfp.jpg') }}" alt="user photo">
            </a>
            <a href="/auth/logout"
                class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0">
                Se déconnecter
            </a>
            {% else %}
            <a href="/auth/login"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0">
                Se connecter
            </a>
            {% endif %}
            <button data-collapse-toggle="navbar-cta" type="button"
                class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
                aria-controls="navbar-cta" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                        clip-rule="evenodd">
                    </path>
                </svg>
            </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
            <ul
                class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white">
                <li>
                    <a href="/"
                        class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0"
                        aria-current="page">Accueil</a>
                </li>
                <li>
                    <p id="dropdownHoverButton" data-dropdown-toggle="dropdownHover" data-dropdown-trigger="hover" class="inline-flex items-center block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 w-full justify-between" type="button">
                        Films
                        <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"></path>
                        </svg>
                    </p>

                    <div id="dropdownHover" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                        <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownHoverButton">
                          <li>
                            <a href="{{ url_for('movie.popular') }}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Populaires</a>
                          </li>
                          <li>
                            <a href="{{ url_for('movie.trending') }}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Du moment</a>
                          </li>
                          <li>
                            <a href="{{ url_for('movie.upcoming') }}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">A venir</a>
                          </li>
                          <li>
                            <a href="{{ url_for('movie.top_rated') }}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Les mieux évalués</a>
                          </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="{{ url_for('person.popular') }}"
                        class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0">Artistes</a>
                </li>
                {% if is_connected %}
                    <li>
                        <a href="{{ url_for('collection.hub') }}"
                            class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0">Mes collections</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        <div class="container mt-20 absolute z-50 m-2">
            {% for category, message in messages %}
                {% set alert_classes = {
                    "info": "text-blue-800 bg-blue-50",
                    "success": "text-green-800 bg-green-50",
                    "warning": "text-yellow-800 bg-yellow-50",
                    "error": "text-red-800 bg-red-50"
                } %}
                <div id="alert-{{ loop.index }}"
                     class="inline-flex items-center p-4 mb-4 rounded-lg {{ alert_classes[category] }}"
                     role="alert"
                     data-timeout="10000">
                  <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                       fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"></path>
                  </svg>
                  <span class="sr-only">{{ category }}</span>
                  <div class="ms-3 text-sm font-medium">
                    {{ message }}
                  </div>
                  <button type="button"
                          class="ms-auto -mx-1.5 -my-1.5 rounded-lg focus:ring-2 p-1.5 hover:bg-opacity-75 inline-flex items-center justify-center h-8 w-8"
                          data-dismiss-target="#alert-{{ loop.index }}" aria-label="Close">
                      <span class="sr-only">Close</span>
                      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                           fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                              stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                      </svg>
                  </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}

<script>
    let lastScrollTop = 0;
    const navbar = document.getElementById('navbar');

    window.addEventListener('scroll', () => {
        const scrollTop = window.pageYOffset || document.documentElement.scrollTop;

        if (scrollTop > lastScrollTop) {
            // Scrolling down
            navbar.style.transform = 'translateY(-100%)';
        } else {
            // Scrolling up
            navbar.style.transform = 'translateY(0)';
        }

        lastScrollTop = scrollTop <= 0 ? 0 : scrollTop; // Avoid negative scroll values
    });

    document.addEventListener('DOMContentLoaded', function() {
        const alerts = document.querySelectorAll('[data-timeout]');
        alerts.forEach(alert => {
            const timeout = parseInt(alert.getAttribute('data-timeout'), 10);
            setTimeout(() => {
                alert.remove();
            }, timeout);
        });
    });
</script>


    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
</body>

</html>